### ISSUE TITLE
Help me with my dumb issue

### ISSUE THREAD

**Issue by pneb** [cesarhuret/docGPT#2]
How do I delete the Ask Chatgpt button thingy? The macro was deleted already and the developers tab is now hidden too

**Comment by cesarhuret** [comment]
Hey @pneb ! 

Thanks for mentioning this! I'll set up a script so that you can delete the Ask ChatGPT button from the Word UI.

:)

**Comment by cesarhuret** [comment]
@pneb

Here's a script for you to delete the button: 

```
Sub DeleteShortcut()
    Dim DeleteControl As CommandBarControl
    For Each DeleteControl In Application.CommandBars("Text").Controls
       If DeleteControl.Caption = "Ask ChatGPT" Then
          DeleteControl.Delete
       End If
    Next DeleteControl
End Sub
```

Create a new macro with the name `DeleteShortcut`

And then hit run 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/67405604/206920692-6dfa0161-78ce-436b-941b-e8ecb712b73a.png">

Hope this helps!
If it works, please can you respond so that I can mark this issue as resolved? 

Thanks,
Cesar Huret

**Comment by pneb** [comment]
> @pneb
> 
> Here's a script for you to delete the button:
> 
> ```
> Sub DeleteShortcut()
>     Dim DeleteControl As CommandBarControl
>     For Each DeleteControl In Application.CommandBars("Text").Controls
>        If DeleteControl.Caption = "Ask ChatGPT" Then
>           DeleteControl.Delete
>        End If
>     Next DeleteControl
> End Sub
> ```
> 
> Create a new macro with the name `DeleteShortcut`
> 
> And then hit run <img alt="image" width="881" src="https://user-images.githubusercontent.com/67405604/206920692-6dfa0161-78ce-436b-941b-e8ecb712b73a.png">
> 
> Hope this helps! If it works, please can you respond so that I can mark this issue as resolved?
> 
> Thanks, Cesar Huret

Yes, it did thanks!
